### ISSUE TITLE
尝试使用预制菜替代外卖 | Mst

### ISSUE THREAD

**Issue by MskTmi** [MskTmi/MskTmi.github.io#40]
https://blog.msktmi.com/posts/2024/1857581413.html? 

 起因最近讨伐预制菜的呼声很高，主要还是因为预制菜冒充现做菜抛开事实不谈，如果点的低价外卖都是预制菜，那为何不直接加入预制菜？选择困难的我在一连看了几个大品牌预制菜后决定丢掉大脑开始踩坑，毕竟吃的东西光看评测也看不出来什么 废话少说，开吃！  注意：本篇文章主观性极强！   吃吃吃卤肉饭 ★★★★★ 居然还有点东西？  味道偏咸一点，但汤汁很下饭，比较适合重口味的人（看来大家说料理包口味偏重不是没有

**Comment by muzeliu** [comment]
支持博主，加油！！！（转发此条文案，每条五毛，记得删除括号里的文字）

**Comment by Revord** [comment]
支持博主，加油！！！（转发此条文案，每条五毛，记得删除括号里的文字）

**Comment by Revord** [comment]
米饭加cheese，你是小天才

**Comment by Revord** [comment]
博主催更！

**Comment by muzeliu** [comment]
博主催更

**Comment by MskTmi** [comment]
> @Revord
> 博主催更！

别催了，饺子爆仓吃不完辣😭
